# Copyright 2019 Endless Mobile, Inc.
# SPDX-License-Identifier: LGPL-2.0-or-later

image: registry.fedoraproject.org/fedora:30

stages:
  - build

before_script:
  - dnf install -y gcc meson ninja-build "pkgconfig(gio-2.0)" "pkgconfig(gio-unix-2.0)" "pkgconfig(glib-2.0)"

build:
  stage: build
  script:
    - meson _build .
    - cd _build
    - ninja
    - meson test
    # Run it again! This previously did not work.
    - meson test
  artifacts:
    when: on_failure
    name: "libglnx-${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"

reuse:
  stage: build
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  before_script: []
  script:
    - reuse lint
